# Generated by Django 4.2 on 2023-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total',
        ),
        migrations.AlterField(
            model_name='report',
            name='cash_reported',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('ny', 'New York'), ('tx', 'Texas')], max_length=2),
        ),
    ]
