# Generated by Django 4.2 on 2023-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_form', '0002_remove_report_difference_remove_report_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('BSP', 'Burrito San Patricio'), ('BSC', 'Burrito Condado'), ('BGH', 'Burger Garden Hills'), ('BGC', 'Burger Condado'), ('BGP', 'Burger Ponce')], max_length=3),
        ),
    ]
